import db from "../config/db.config.js";
import {
  Provinsi,
  Kabupaten,
  Kecamatan,
  DesaAdat
} from "../models/associations.js";

export const seederWilayahBali = async () => {
  let t;

  try {
    const rawData = [
      { desa: "Kalianget", kec: "Seririt", kab: "Buleleng" },
      { desa: "Joanyar Kajanan", kec: "Seririt", kab: "Buleleng" },
      { desa: "Joanyar Kelodan", kec: "Seririt", kab: "Buleleng" },
      { desa: "Tangguwisia", kec: "Seririt", kab: "Buleleng" },
      { desa: "Sulanyah", kec: "Seririt", kab: "Buleleng" },
      { desa: "Bubunan", kec: "Seririt", kab: "Buleleng" },
      { desa: "Ringdikit", kec: "Seririt", kab: "Buleleng" },
      { desa: "Rangdu", kec: "Seririt", kab: "Buleleng" },
      { desa: "Mayong", kec: "Seririt", kab: "Buleleng" },
      { desa: "Tunju", kec: "Seririt", kab: "Buleleng" },
      { desa: "Bestala", kec: "Seririt", kab: "Buleleng" },
      { desa: "Munduk Bestala", kec: "Seririt", kab: "Buleleng" },
      { desa: "Patemon", kec: "Seririt", kab: "Buleleng" },
      { desa: "Lokapaksa", kec: "Seririt", kab: "Buleleng" },
      { desa: "Ularan", kec: "Seririt", kab: "Buleleng" },
      { desa: "Unggahan", kec: "Seririt", kab: "Buleleng" },
      { desa: "Umeanyar", kec: "Seririt", kab: "Buleleng" },
      { desa: "Banjarasem", kec: "Seririt", kab: "Buleleng" },
      { desa: "Yehanakan", kec: "Seririt", kab: "Buleleng" },
      { desa: "Kalanganyar", kec: "Seririt", kab: "Buleleng" },
      { desa: "Kalisada", kec: "Seririt", kab: "Buleleng" },
      { desa: "Tegallenga", kec: "Seririt", kab: "Buleleng" },
      { desa: "Pangkungparuk", kec: "Seririt", kab: "Buleleng" },
      { desa: "Pengastulan", kec: "Seririt", kab: "Buleleng" },
      { desa: "Seririt", kec: "Seririt", kab: "Buleleng" },
      { desa: "Kalibukbuk", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Banyualit", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Anturan", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Dharmajati Tukadmungga", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Pemaron", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Tista", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Bangkang", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Galiran", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Runuh", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Nagesepeha", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Petandakan", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Penglatan", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Alapsari", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Bale Agung Tenaon", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Poh Bergong", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Beratan Samayaji", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Banyuning", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Padangkeling", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Banyuasri", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Buleleng", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Penarukan", kec: "Buleleng", kab: "Buleleng" },
      { desa: "Panji", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Silangjana", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Gunung Luwih", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Pumahan", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Pancasari", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Wanagiri", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Sambangan", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Selat Pandan Banten", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Kayuputih", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Sinalud", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Pegadungan", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Pasut Katiasa", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Batu Dingding", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Amerta Sari", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Padangbulia", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Ambengan", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Munduk Kunci", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Mujung Sari Kerthi", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Sukasada", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Lumbanan", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Sangket", kec: "Sukasada", kab: "Buleleng" },
      { desa: "Tukad Sumaga", kec: "Gerokgak", kab: "Buleleng" },
      { desa: "Celukan Bawang", kec: "Gerokgak", kab: "Buleleng" },
      { desa: "Tinga-tinga", kec: "Gerokgak", kab: "Buleleng" },
      { desa: "Pengulon", kec: "Gerokgak", kab: "Buleleng" },
      { desa: "Patas", kec: "Gerokgak", kab: "Buleleng" },
      { desa: "Gerokgak", kec: "Gerokgak", kab: "Buleleng" },
      { desa: "Sanggalangit", kec: "Gerokgak", kab: "Buleleng" },
      { desa: "Musi", kec: "Gerokgak", kab: "Buleleng" },
      { desa: "Penyabangan", kec: "Gerokgak", kab: "Buleleng" },
      { desa: "Banyupoh", kec: "Gerokgak", kab: "Buleleng" },
      { desa: "Pemuteran", kec: "Gerokgak", kab: "Buleleng" },
      { desa: "Sumberkima", kec: "Gerokgak", kab: "Buleleng" },
      { desa: "Pejarakan", kec: "Gerokgak", kab: "Buleleng" },
      { desa: "Sumberklampok", kec: "Gerokgak", kab: "Buleleng" },
      { desa: "Busungbiu", kec: "Busungbiu", kab: "Buleleng" },
      { desa: "Kekeran", kec: "Busungbiu", kab: "Buleleng" },
      { desa: "Pelapuan", kec: "Busungbiu", kab: "Buleleng" },
      { desa: "Bengkel", kec: "Busungbiu", kab: "Buleleng" },
      { desa: "Umejero", kec: "Busungbiu", kab: "Buleleng" },
      { desa: "Kedis", kec: "Busungbiu", kab: "Buleleng" },
      { desa: "Subuk", kec: "Busungbiu", kab: "Buleleng" },
      { desa: "Tinggarsari", kec: "Busungbiu", kab: "Buleleng" },
      { desa: "Titab", kec: "Busungbiu", kab: "Buleleng" },
      { desa: "Telaga", kec: "Busungbiu", kab: "Buleleng" },
      { desa: "Bongancina", kec: "Busungbiu", kab: "Buleleng" },
      { desa: "Pucaksari", kec: "Busungbiu", kab: "Buleleng" },
      { desa: "Tista", kec: "Busungbiu", kab: "Buleleng" },
      { desa: "Munduk Mengenu", kec: "Busungbiu", kab: "Buleleng" },
      { desa: "Munduk Tengah", kec: "Busungbiu", kab: "Buleleng" },
      { desa: "Sepang", kec: "Busungbiu", kab: "Buleleng" },
      { desa: "Banjar", kec: "Banjar", kab: "Buleleng" },
      { desa: "Pedawa", kec: "Banjar", kab: "Buleleng" },
      { desa: "Banjar Tegeha", kec: "Banjar", kab: "Buleleng" },
      { desa: "Dencarik", kec: "Banjar", kab: "Buleleng" },
      { desa: "Kaliasem", kec: "Banjar", kab: "Buleleng" },
      { desa: "Tigawasa", kec: "Banjar", kab: "Buleleng" },
      { desa: "Temukus", kec: "Banjar", kab: "Buleleng" },
      { desa: "Cempaga", kec: "Banjar", kab: "Buleleng" },
      { desa: "Sidetapa", kec: "Banjar", kab: "Buleleng" },
      { desa: "Tampekan", kec: "Banjar", kab: "Buleleng" },
      { desa: "Banyuseri", kec: "Banjar", kab: "Buleleng" },
      { desa: "Tirtasari", kec: "Banjar", kab: "Buleleng" },
      { desa: "Kayuputih", kec: "Banjar", kab: "Buleleng" },
      { desa: "Banyuatis", kec: "Banjar", kab: "Buleleng" },
      { desa: "Gobleg", kec: "Banjar", kab: "Buleleng" },
      { desa: "Gesing", kec: "Banjar", kab: "Buleleng" },
      { desa: "Munduk", kec: "Banjar", kab: "Buleleng" },
      { desa: "Tamblingan", kec: "Banjar", kab: "Buleleng" },
      { desa: "Bukti", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Yeh Sanih", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Kubutambahan", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Bengkala", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Bila Bajang", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Bila Tua", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Tamblang", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Tangkid", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Kelampuak", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Bontihing", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Rendetin", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Pakisan", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Sangburni", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Kelandis", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Mengandang", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Tegal", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Tambakan", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Tajun", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Bayad", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Tunjung", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Depeha", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Bulian", kec: "Kubutambahan", kab: "Buleleng" },
      { desa: "Sembiran", kec: "Tejakula", kab: "Buleleng" },
      { desa: "Pacung", kec: "Tejakula", kab: "Buleleng" },
      { desa: "Bangkah", kec: "Tejakula", kab: "Buleleng" },
      { desa: "Julah", kec: "Tejakula", kab: "Buleleng" },
      { desa: "Madenan", kec: "Tejakula", kab: "Buleleng" },
      { desa: "Sangambu", kec: "Tejakula", kab: "Buleleng" },
      { desa: "Gentuh", kec: "Tejakula", kab: "Buleleng" },
      { desa: "Keduran", kec: "Tejakula", kab: "Buleleng" },
      { desa: "Bondalem", kec: "Tejakula", kab: "Buleleng" },
      { desa: "Tejakula", kec: "Tejakula", kab: "Buleleng" },
      { desa: "Les-Penuktukan", kec: "Tejakula", kab: "Buleleng" },
      { desa: "Sambirenteng", kec: "Tejakula", kab: "Buleleng" },
      { desa: "Gretek", kec: "Tejakula", kab: "Buleleng" },
      { desa: "Tembok", kec: "Tejakula", kab: "Buleleng" },
      { desa: "Ngis", kec: "Tejakula", kab: "Buleleng" },
      { desa: "Sudaji", kec: "Sawan", kab: "Buleleng" },
      { desa: "Menyali", kec: "Sawan", kab: "Buleleng" },
      { desa: "Bebetin", kec: "Sawan", kab: "Buleleng" },
      { desa: "Manuksesa", kec: "Sawan", kab: "Buleleng" },
      { desa: "Jagaraga", kec: "Sawan", kab: "Buleleng" },
      { desa: "Lemukih", kec: "Sawan", kab: "Buleleng" },
      { desa: "Sinabun", kec: "Sawan", kab: "Buleleng" },
      { desa: "Suwug", kec: "Sawan", kab: "Buleleng" },
      { desa: "Sawan", kec: "Sawan", kab: "Buleleng" },
      { desa: "Galungan", kec: "Sawan", kab: "Buleleng" },
      { desa: "Kerobokan", kec: "Sawan", kab: "Buleleng" },
      { desa: "Kloncing", kec: "Sawan", kab: "Buleleng" },
      { desa: "Bungkulan", kec: "Sawan", kab: "Buleleng" },
      { desa: "Sari Besikan", kec: "Sawan", kab: "Buleleng" },
      { desa: "Sangsit Dauh Yeh", kec: "Sawan", kab: "Buleleng" },
      { desa: "Sangsit Dangin Yeh", kec: "Sawan", kab: "Buleleng" },
      { desa: "Sekumpul", kec: "Sawan", kab: "Buleleng" },
      { desa: "Lebah", kec: "Sawan", kab: "Buleleng" },
      { desa: "Pengragoan Dangin Tukad", kec: "Pakutatan", kab: "Jembrana" },
      { desa: "Pengragoan Dauh Tukad", kec: "Pakutatan", kab: "Jembrana" },
      { desa: "Badingkayu", kec: "Pakutatan", kab: "Jembrana" },
      { desa: "Mengenuanyar", kec: "Pakutatan", kab: "Jembrana" },
      { desa: "Pasut", kec: "Pakutatan", kab: "Jembrana" },
      { desa: "Gumbrih", kec: "Pakutatan", kab: "Jembrana" },
      { desa: "Pangyangan", kec: "Pakutatan", kab: "Jembrana" },
      { desa: "Pakutatan", kec: "Pakutatan", kab: "Jembrana" },
      { desa: "Asah Duren", kec: "Pakutatan", kab: "Jembrana" },
      { desa: "Manggissari", kec: "Pakutatan", kab: "Jembrana" },
      { desa: "Juwuk Manis", kec: "Pakutatan", kab: "Jembrana" },
      { desa: "Pulukan", kec: "Pakutatan", kab: "Jembrana" },
      { desa: "Medewi", kec: "Pakutatan", kab: "Jembrana" },
      { desa: "Yeh Sumbul", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Yehembang Kangin", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Nusamara", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Yehembang", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Giri Gahana Grama", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Yehembang Kauh", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Munduk Anggrek Kaja", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Yehbuah", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Kedisan", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Penyaringan", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Giri Amerta", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Giri Utama", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Delodbrawah", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Pohsanten", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Pergung", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Mendoyo Dangin Tukad", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Mendoyo Dauh Tukad", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Tegalcangkring", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Taman Sari", kec: "Mendoyo", kab: "Jembrana" },
      { desa: "Dangintukadaya", kec: "Jembrana", kab: "Jembrana" },
      { desa: "Batuagung", kec: "Jembrana", kab: "Jembrana" },
      { desa: "Budeng", kec: "Jembrana", kab: "Jembrana" },
      { desa: "Yehkuning", kec: "Jembrana", kab: "Jembrana" },
      { desa: "Perancak", kec: "Jembrana", kab: "Jembrana" },
      { desa: "Sangkaragung", kec: "Jembrana", kab: "Jembrana" },
      { desa: "Dauhwaru", kec: "Jembrana", kab: "Jembrana" },
      { desa: "Lokasari", kec: "Jembrana", kab: "Jembrana" },
      { desa: "Kertha Jaya Pendem", kec: "Jembrana", kab: "Jembrana" },
      { desa: "Berangbang", kec: "Negara", kab: "Jembrana" },
      { desa: "Dharma Kerti", kec: "Negara", kab: "Jembrana" },
      { desa: "Dharma laksana", kec: "Negara", kab: "Jembrana" },
      { desa: "Tegalbadeng Kangin", kec: "Negara", kab: "Jembrana" },
      { desa: "Tegalbadeng Kauh", kec: "Negara", kab: "Jembrana" },
      { desa: "Baluk", kec: "Negara", kab: "Jembrana" },
      { desa: "Banyubiru", kec: "Negara", kab: "Jembrana" },
      { desa: "Baler Bale Agung", kec: "Negara", kab: "Jembrana" },
      { desa: "Puseh Agung", kec: "Negara", kab: "Jembrana" },
      { desa: "Lelateng", kec: "Negara", kab: "Jembrana" },
      { desa: "Melaya", kec: "Melaya", kab: "Jembrana" },
      { desa: "Sumbersari", kec: "Melaya", kab: "Jembrana" },
      { desa: "Nusasari", kec: "Melaya", kab: "Jembrana" },
      { desa: "Wanasari", kec: "Melaya", kab: "Jembrana" },
      { desa: "Ekasari", kec: "Melaya", kab: "Jembrana" },
      { desa: "Palalinggah", kec: "Melaya", kab: "Jembrana" },
      { desa: "Candikusuma", kec: "Melaya", kab: "Jembrana" },
      { desa: "Tuwed", kec: "Melaya", kab: "Jembrana" },
      { desa: "Tukadaya", kec: "Melaya", kab: "Jembrana" },
      { desa: "Tamansari", kec: "Melaya", kab: "Jembrana" },
      { desa: "Berawangtangi", kec: "Melaya", kab: "Jembrana" },
      { desa: "Manistutu", kec: "Melaya", kab: "Jembrana" },
      { desa: "Gilimanuk", kec: "Melaya", kab: "Jembrana" },
      { desa: "Pengotan", kec: "Bangli", kab: "Bangli" },
      { desa: "Bangklet", kec: "Bangli", kab: "Bangli" },
      { desa: "Kayubihi", kec: "Bangli", kab: "Bangli" },
      { desa: "Kayang", kec: "Bangli", kab: "Bangli" },
      { desa: "Umanyar", kec: "Bangli", kab: "Bangli" },
      { desa: "Kuning", kec: "Bangli", kab: "Bangli" },
      { desa: "Tamanbali", kec: "Bangli", kab: "Bangli" },
      { desa: "Jelekungkang", kec: "Bangli", kab: "Bangli" },
      { desa: "Guliang Kangin", kec: "Bangli", kab: "Bangli" },
      { desa: "Guliang Kawan", kec: "Bangli", kab: "Bangli" },
      { desa: "Bunutin", kec: "Bangli", kab: "Bangli" },
      { desa: "Langkan", kec: "Bangli", kab: "Bangli" },
      { desa: "Palaktiying", kec: "Bangli", kab: "Bangli" },
      { desa: "Buayang", kec: "Bangli", kab: "Bangli" },
      { desa: "Landih", kec: "Bangli", kab: "Bangli" },
      { desa: "Penaga", kec: "Bangli", kab: "Bangli" },
      { desa: "Penglipuran", kec: "Bangli", kab: "Bangli" },
      { desa: "Kubu", kec: "Bangli", kab: "Bangli" },
      { desa: "Sidembunut", kec: "Bangli", kab: "Bangli" },
      { desa: "Cempaga", kec: "Bangli", kab: "Bangli" },
      { desa: "Tegallalang", kec: "Bangli", kab: "Bangli" },
      { desa: "Kawan", kec: "Bangli", kab: "Bangli" },
      { desa: "Bebalang", kec: "Bangli", kab: "Bangli" },
      { desa: "Penglumbaran Kawan", kec: "Susut", kab: "Bangli" },
      { desa: "Tiga Kawan", kec: "Susut", kab: "Bangli" },
      { desa: "Serai Kembangmerta", kec: "Susut", kab: "Bangli" },
      { desa: "Seribatu", kec: "Susut", kab: "Bangli" },
      { desa: "Malet Gusti", kec: "Susut", kab: "Bangli" },
      { desa: "Temen", kec: "Susut", kab: "Bangli" },
      { desa: "Mancingan", kec: "Susut", kab: "Bangli" },
      { desa: "Malet Kutamesir", kec: "Susut", kab: "Bangli" },
      { desa: "Malet Tengah", kec: "Susut", kab: "Bangli" },
      { desa: "Pukuh", kec: "Susut", kab: "Bangli" },
      { desa: "Kayuambua", kec: "Susut", kab: "Bangli" },
      { desa: "Linjong", kec: "Susut", kab: "Bangli" },
      { desa: "Temaga", kec: "Susut", kab: "Bangli" },
      { desa: "Buungan", kec: "Susut", kab: "Bangli" },
      { desa: "Tiga", kec: "Susut", kab: "Bangli" },
      { desa: "Penglumbaran Kangin", kec: "Susut", kab: "Bangli" },
      { desa: "Lumbuan", kec: "Susut", kab: "Bangli" },
      { desa: "Alisbintang", kec: "Susut", kab: "Bangli" },
      { desa: "Bungkuan", kec: "Susut", kab: "Bangli" },
      { desa: "Cekeng", kec: "Susut", kab: "Bangli" },
      { desa: "Tanggahan Gunung", kec: "Susut", kab: "Bangli" },
      { desa: "Tanggahan Peken", kec: "Susut", kab: "Bangli" },
      { desa: "Sulahan", kec: "Susut", kab: "Bangli" },
      { desa: "Kikian", kec: "Susut", kab: "Bangli" },
      { desa: "Kebon", kec: "Susut", kab: "Bangli" },
      { desa: "Susut Kaja", kec: "Susut", kab: "Bangli" },
      { desa: "Susut Kelod", kec: "Susut", kab: "Bangli" },
      { desa: "Manuk", kec: "Susut", kab: "Bangli" },
      { desa: "Juwukbali", kec: "Susut", kab: "Bangli" },
      { desa: "Penatahan", kec: "Susut", kab: "Bangli" },
      { desa: "Lebah", kec: "Susut", kab: "Bangli" },
      { desa: "Pukuh", kec: "Susut", kab: "Bangli" },
      { desa: "Tangkas", kec: "Susut", kab: "Bangli" },
      { desa: "Demulih", kec: "Susut", kab: "Bangli" },
      { desa: "Tanggahan Tengah", kec: "Susut", kab: "Bangli" },
      { desa: "Tanggahan Talang Jiwa", kec: "Susut", kab: "Bangli" },
      { desa: "Sala", kec: "Susut", kab: "Bangli" },
      { desa: "Abuan", kec: "Susut", kab: "Bangli" },
      { desa: "Serokadan", kec: "Susut", kab: "Bangli" },
      { desa: "Apuan", kec: "Susut", kab: "Bangli" },
      { desa: "Bangun Lemah Kawan", kec: "Susut", kab: "Bangli" },
      { desa: "Bangun Lemah Kangin", kec: "Susut", kab: "Bangli" },
      { desa: "Selat", kec: "Susut", kab: "Bangli" },
      { desa: "Pengiangan Kawan", kec: "Susut", kab: "Bangli" },
      { desa: "Pengiangan Kangin", kec: "Susut", kab: "Bangli" },
      { desa: "Songlandak", kec: "Susut", kab: "Bangli" },
      { desa: "Selatnyuhan", kec: "Susut", kab: "Bangli" },
      { desa: "Jehem", kec: "Tembuku", kab: "Bangli" },
      { desa: "Tingkadbatu", kec: "Tembuku", kab: "Bangli" },
      { desa: "Sama Undisan", kec: "Tembuku", kab: "Bangli" },
      { desa: "Tambahan", kec: "Tembuku", kab: "Bangli" },
      { desa: "Geria Kelempung", kec: "Tembuku", kab: "Bangli" },
      { desa: "Galiran", kec: "Tembuku", kab: "Bangli" },
      { desa: "Antugan", kec: "Tembuku", kab: "Bangli" },
      { desa: "Sama Geria", kec: "Tembuku", kab: "Bangli" },
      { desa: "Kaulan Dewa Jehem Kelod", kec: "Tembuku", kab: "Bangli" },
      { desa: "Tabunan", kec: "Tembuku", kab: "Bangli" },
      { desa: "Undisan Kaja", kec: "Tembuku", kab: "Bangli" },
      { desa: "Undisan Kelod", kec: "Tembuku", kab: "Bangli" },
      { desa: "Sekaan", kec: "Tembuku", kab: "Bangli" },
      { desa: "Bangbang", kec: "Tembuku", kab: "Bangli" },
      { desa: "Cepunggung", kec: "Tembuku", kab: "Bangli" },
      { desa: "Bangkiangsidem", kec: "Tembuku", kab: "Bangli" },
      { desa: "Nyanglan Kaja", kec: "Tembuku", kab: "Bangli" },
      { desa: "Metra", kec: "Tembuku", kab: "Bangli" },
      { desa: "Yangapi", kec: "Tembuku", kab: "Bangli" },
      { desa: "Umbalan", kec: "Tembuku", kab: "Bangli" },
      { desa: "Penida Kaja", kec: "Tembuku", kab: "Bangli" },
      { desa: "Kedui", kec: "Tembuku", kab: "Bangli" },
      { desa: "Tembuku Kaja", kec: "Tembuku", kab: "Bangli" },
      { desa: "Tegalasah Kelod", kec: "Tembuku", kab: "Bangli" },
      { desa: "Tembuku Kelod", kec: "Tembuku", kab: "Bangli" },
      { desa: "Tegalasah Kaja", kec: "Tembuku", kab: "Bangli" },
      { desa: "Penida Kelod", kec: "Tembuku", kab: "Bangli" },
      { desa: "Penarukan", kec: "Tembuku", kab: "Bangli" },
      { desa: "Karang Suung Kelod", kec: "Tembuku", kab: "Bangli" },
      { desa: "Peninjoan", kec: "Tembuku", kab: "Bangli" },
      { desa: "Tampuagan", kec: "Tembuku", kab: "Bangli" },
      { desa: "Kebon", kec: "Tembuku", kab: "Bangli" },
      { desa: "Bengang", kec: "Tembuku", kab: "Bangli" },
      { desa: "Payuk", kec: "Tembuku", kab: "Bangli" },
      { desa: "Manikaji", kec: "Tembuku", kab: "Bangli" },
      { desa: "Karang Suung Kaja", kec: "Tembuku", kab: "Bangli" },
      { desa: "Pulesari", kec: "Tembuku", kab: "Bangli" },
      { desa: "Awan", kec: "Kintamani", kab: "Bangli" },
      { desa: "Abangsongan", kec: "Kintamani", kab: "Bangli" },
      { desa: "Abang Batudinding", kec: "Kintamani", kab: "Bangli" },
      { desa: "Abuan", kec: "Kintamani", kab: "Bangli" },
      { desa: "Bayunggede", kec: "Kintamani", kab: "Bangli" },
      { desa: "Bayung Cerik", kec: "Kintamani", kab: "Bangli" },
      { desa: "Belancan", kec: "Kintamani", kab: "Bangli" },
      { desa: "Bukih", kec: "Kintamani", kab: "Bangli" },
      { desa: "Batukaang", kec: "Kintamani", kab: "Bangli" },
      { desa: "Bunutin", kec: "Kintamani", kab: "Bangli" },
      { desa: "Binyan", kec: "Kintamani", kab: "Bangli" },
      { desa: "Belanga", kec: "Kintamani", kab: "Bangli" },
      { desa: "Bantang", kec: "Kintamani", kab: "Bangli" },
      { desa: "Panti", kec: "Kintamani", kab: "Bangli" },
      { desa: "Selulung", kec: "Kintamani", kab: "Bangli" },
      { desa: "Bonyoh", kec: "Kintamani", kab: "Bangli" },
      { desa: "Binyan (buahan)", kec: "Kintamani", kab: "Bangli" },
      { desa: "Buahan", kec: "Kintamani", kab: "Bangli" },
      { desa: "Belandingan", kec: "Kintamani", kab: "Bangli" },
      { desa: "Banua", kec: "Kintamani", kab: "Bangli" },
      { desa: "Batur", kec: "Kintamani", kab: "Bangli" },
      { desa: "Catur", kec: "Kintamani", kab: "Bangli" },
      { desa: "Daup", kec: "Kintamani", kab: "Bangli" },
      { desa: "Dausa", kec: "Kintamani", kab: "Bangli" },
      { desa: "Cenigaan", kec: "Kintamani", kab: "Bangli" },
      { desa: "Lateng", kec: "Kintamani", kab: "Bangli" },
      { desa: "Gunung Bau", kec: "Kintamani", kab: "Bangli" },
      { desa: "Katung", kec: "Kintamani", kab: "Bangli" },
      { desa: "Kutuh", kec: "Kintamani", kab: "Bangli" },
      { desa: "Angansari", kec: "Kintamani", kab: "Bangli" },
      { desa: "Kintamani", kec: "Kintamani", kab: "Bangli" },
      { desa: "Glagalinggah", kec: "Kintamani", kab: "Bangli" },
      { desa: "Kayukapas", kec: "Kintamani", kab: "Bangli" },
      { desa: "Kedisan", kec: "Kintamani", kab: "Bangli" },
      { desa: "Langgahan", kec: "Kintamani", kab: "Bangli" },
      { desa: "Lembean", kec: "Kintamani", kab: "Bangli" },
      { desa: "Mangguh", kec: "Kintamani", kab: "Bangli" },
      { desa: "Manikliyu", kec: "Kintamani", kab: "Bangli" },
      { desa: "Pinggan", kec: "Kintamani", kab: "Bangli" },
      { desa: "Mengani", kec: "Kintamani", kab: "Bangli" },
      { desa: "Pengejaran", kec: "Kintamani", kab: "Bangli" },
      { desa: "Sekaan", kec: "Kintamani", kab: "Bangli" },
      { desa: "Serai", kec: "Kintamani", kab: "Bangli" },
      { desa: "Satra", kec: "Kintamani", kab: "Bangli" },
      { desa: "Sanda", kec: "Kintamani", kab: "Bangli" },
      { desa: "Tanah Embut", kec: "Kintamani", kab: "Bangli" },
      { desa: "Batupalah", kec: "Kintamani", kab: "Bangli" },
      { desa: "Kembangsari", kec: "Kintamani", kab: "Bangli" },
      { desa: "Tanah Gambir", kec: "Kintamani", kab: "Bangli" },
      { desa: "Kubusalya", kec: "Kintamani", kab: "Bangli" },
      { desa: "Sukawana", kec: "Kintamani", kab: "Bangli" },
      { desa: "Kuum", kec: "Kintamani", kab: "Bangli" },
      { desa: "Bukitsari", kec: "Kintamani", kab: "Bangli" },
      { desa: "Songan", kec: "Kintamani", kab: "Bangli" },
      { desa: "Subaya", kec: "Kintamani", kab: "Bangli" },
      { desa: "Siakin", kec: "Kintamani", kab: "Bangli" },
      { desa: "Batih", kec: "Kintamani", kab: "Bangli" },
      { desa: "Sekardadi", kec: "Kintamani", kab: "Bangli" },
      { desa: "Suter", kec: "Kintamani", kab: "Bangli" },
      { desa: "Terunyan", kec: "Kintamani", kab: "Bangli" },
      { desa: "Ulian", kec: "Kintamani", kab: "Bangli" },
      { desa: "Pecatu", kec: "Kuta Selatan", kab: "Badung" },
      { desa: "Ungasan", kec: "Kuta Selatan", kab: "Badung" },
      { desa: "Kutuh", kec: "Kuta Selatan", kab: "Badung" },
      { desa: "Jimbaran", kec: "Kuta Selatan", kab: "Badung" },
      { desa: "Tanjung Benoa", kec: "Kuta Selatan", kab: "Badung" },
      { desa: "Tengkulung", kec: "Kuta Selatan", kab: "Badung" },
      { desa: "Kampial", kec: "Kuta Selatan", kab: "Badung" },
      { desa: "Peminge", kec: "Kuta Selatan", kab: "Badung" },
      { desa: "Bualu", kec: "Kuta Selatan", kab: "Badung" },
      { desa: "Seminyak", kec: "Kuta", kab: "Badung" },
      { desa: "Legian", kec: "Kuta", kab: "Badung" },
      { desa: "Kuta", kec: "Kuta", kab: "Badung" },
      { desa: "Tuban", kec: "Kuta", kab: "Badung" },
      { desa: "Kelan", kec: "Kuta", kab: "Badung" },
      { desa: "Kedonganan", kec: "Kuta", kab: "Badung" },
      { desa: "Padonan", kec: "Kuta Utara", kab: "Badung" },
      { desa: "Tandeg", kec: "Kuta Utara", kab: "Badung" },
      { desa: "Berawa", kec: "Kuta Utara", kab: "Badung" },
      { desa: "Canggu", kec: "Kuta Utara", kab: "Badung" },
      { desa: "Tuka", kec: "Kuta Utara", kab: "Badung" },
      { desa: "Dalung", kec: "Kuta Utara", kab: "Badung" },
      { desa: "Padangluwih", kec: "Kuta Utara", kab: "Badung" },
      { desa: "Kerobokan", kec: "Kuta Utara", kab: "Badung" },
      { desa: "Cemagi", kec: "Mengwi", kab: "Badung" },
      { desa: "Seseh", kec: "Mengwi", kab: "Badung" },
      { desa: "Mengening", kec: "Mengwi", kab: "Badung" },
      { desa: "Sogsogan", kec: "Mengwi", kab: "Badung" },
      { desa: "Munggu", kec: "Mengwi", kab: "Badung" },
      { desa: "Pande Munggu", kec: "Mengwi", kab: "Badung" },
      { desa: "Kertha Bujangga", kec: "Mengwi", kab: "Badung" },
      { desa: "Pererenan", kec: "Mengwi", kab: "Badung" },
      { desa: "Tumbak Bayuh", kec: "Mengwi", kab: "Badung" },
      { desa: "Buduk", kec: "Mengwi", kab: "Badung" },
      { desa: "Kekeran", kec: "Mengwi", kab: "Badung" },
      { desa: "Beringkit", kec: "Mengwi", kab: "Badung" },
      { desa: "Mengwitani", kec: "Mengwi", kab: "Badung" },
      { desa: "Mengwi", kec: "Mengwi", kab: "Badung" },
      { desa: "Gulingan", kec: "Mengwi", kab: "Badung" },
      { desa: "Penarungan", kec: "Mengwi", kab: "Badung" },
      { desa: "Cemenggon", kec: "Mengwi", kab: "Badung" },
      { desa: "Banjarsayan", kec: "Mengwi", kab: "Badung" },
      { desa: "Denkayu", kec: "Mengwi", kab: "Badung" },
      { desa: "Baha", kec: "Mengwi", kab: "Badung" },
      { desa: "Cengkok", kec: "Mengwi", kab: "Badung" },
      { desa: "Sobangan", kec: "Mengwi", kab: "Badung" },
      { desa: "Dukuh Moncos", kec: "Mengwi", kab: "Badung" },
      { desa: "Sembung", kec: "Mengwi", kab: "Badung" },
      { desa: "Sembung Sobangan", kec: "Mengwi", kab: "Badung" },
      { desa: "Karangenjung", kec: "Mengwi", kab: "Badung" },
      { desa: "Balangan", kec: "Mengwi", kab: "Badung" },
      { desa: "Kuwum Nyelati", kec: "Mengwi", kab: "Badung" },
      { desa: "Abianbase", kec: "Mengwi", kab: "Badung" },
      { desa: "Semate", kec: "Mengwi", kab: "Badung" },
      { desa: "Tangeb", kec: "Mengwi", kab: "Badung" },
      { desa: "Kapal", kec: "Mengwi", kab: "Badung" },
      { desa: "Sempidi", kec: "Mengwi", kab: "Badung" },
      { desa: "Kwanji", kec: "Mengwi", kab: "Badung" },
      { desa: "Sading", kec: "Mengwi", kab: "Badung" },
      { desa: "Lukluk", kec: "Mengwi", kab: "Badung" },
      { desa: "Perang", kec: "Mengwi", kab: "Badung" },
      { desa: "Anggungan", kec: "Mengwi", kab: "Badung" },
      { desa: "Sibangkaja", kec: "Abiansemal", kab: "Badung" },
      { desa: "Lambing Sibangkaja", kec: "Abiansemal", kab: "Badung" },
      { desa: "Sibanggede", kec: "Abiansemal", kab: "Badung" },
      { desa: "Angantaka", kec: "Abiansemal", kab: "Badung" },
      { desa: "Kekeran", kec: "Abiansemal", kab: "Badung" },
      { desa: "Bongkasa", kec: "Abiansemal", kab: "Badung" },
      { desa: "Kutaraga", kec: "Abiansemal", kab: "Badung" },
      { desa: "Karang Dalem", kec: "Abiansemal", kab: "Badung" },
      { desa: "Selat", kec: "Abiansemal", kab: "Badung" },
      { desa: "Mambal", kec: "Abiansemal", kab: "Badung" },
      { desa: "Baturning", kec: "Abiansemal", kab: "Badung" },
      { desa: "Semana", kec: "Abiansemal", kab: "Badung" },
      { desa: "Umahanyar", kec: "Abiansemal", kab: "Badung" },
      { desa: "Gerih", kec: "Abiansemal", kab: "Badung" },
      { desa: "Abiansemal", kec: "Abiansemal", kab: "Badung" },
      { desa: "Taman", kec: "Abiansemal", kab: "Badung" },
      { desa: "Batubayan", kec: "Abiansemal", kab: "Badung" },
      { desa: "Jempeng", kec: "Abiansemal", kab: "Badung" },
      { desa: "Punggul", kec: "Abiansemal", kab: "Badung" },
      { desa: "Sigaran", kec: "Abiansemal", kab: "Badung" },
      { desa: "Tingas", kec: "Abiansemal", kab: "Badung" },
      { desa: "Lambing", kec: "Abiansemal", kab: "Badung" },
      { desa: "Bindu", kec: "Abiansemal", kab: "Badung" },
      { desa: "Samu", kec: "Abiansemal", kab: "Badung" },
      { desa: "Ayunan", kec: "Abiansemal", kab: "Badung" },
      { desa: "Ambengan", kec: "Abiansemal", kab: "Badung" },
      { desa: "Tegal", kec: "Abiansemal", kab: "Badung" },
      { desa: "Darmasaba", kec: "Abiansemal", kab: "Badung" },
      { desa: "Pikah", kec: "Abiansemal", kab: "Badung" },
      { desa: "Blahkiuh", kec: "Abiansemal", kab: "Badung" },
      { desa: "Jagapati", kec: "Abiansemal", kab: "Badung" },
      { desa: "Sedang", kec: "Abiansemal", kab: "Badung" },
      { desa: "Sangeh", kec: "Abiansemal", kab: "Badung" },
      { desa: "Gerana", kec: "Abiansemal", kab: "Badung" },
      { desa: "Samuan", kec: "Petang", kab: "Badung" },
      { desa: "Anggungan", kec: "Petang", kab: "Badung" },
      { desa: "Carangsari", kec: "Petang", kab: "Badung" },
      { desa: "Getasan", kec: "Petang", kab: "Badung" },
      { desa: "Pangsan", kec: "Petang", kab: "Badung" },
      { desa: "Petang", kec: "Petang", kab: "Badung" },
      { desa: "Kerta", kec: "Petang", kab: "Badung" },
      { desa: "Lipah", kec: "Petang", kab: "Badung" },
      { desa: "Munduk Damping", kec: "Petang", kab: "Badung" },
      { desa: "Angantiga", kec: "Petang", kab: "Badung" },
      { desa: "Sulangai", kec: "Petang", kab: "Badung" },
      { desa: "Batulantang", kec: "Petang", kab: "Badung" },
      { desa: "Sandakan", kec: "Petang", kab: "Badung" },
      { desa: "Nungnung", kec: "Petang", kab: "Badung" },
      { desa: "Auman", kec: "Petang", kab: "Badung" },
      { desa: "Pelaga", kec: "Petang", kab: "Badung" },
      { desa: "Tinggan", kec: "Petang", kab: "Badung" },
      { desa: "Bukian", kec: "Petang", kab: "Badung" },
      { desa: "Semanik", kec: "Petang", kab: "Badung" },
      { desa: "Tiyingan", kec: "Petang", kab: "Badung" },
      { desa: "Kiadan", kec: "Petang", kab: "Badung" },
      { desa: "Bon", kec: "Petang", kab: "Badung" },
      { desa: "Lawak", kec: "Petang", kab: "Badung" },
      { desa: "Jempanang", kec: "Petang", kab: "Badung" },
      { desa: "Belok", kec: "Petang", kab: "Badung" },
      { desa: "Sekarmukti", kec: "Petang", kab: "Badung" },
      { desa: "Sidan", kec: "Petang", kab: "Badung" },
      { desa: "Tegenungan", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Kemenuh", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Sumampan", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Tengkulak Kelod", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Tengkulak Kaja", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Tengkulak Tengah", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Gangangan Cangi", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Gerih", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Lantangidung", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Batuan", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Negara", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Sukawati", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Guwang", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Ketewel", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Rangkan", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Lembeng", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Batuyang", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Batuaji", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Jero Kuta", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Dlod Tukad", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Teggaltamu", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Celuk", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Tangsub", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Cemenggaon", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Singapadu", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Kebon", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Negari", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Belaluan", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Kutri", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Griya Kutri", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Belang Kaler", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Belang Samu", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Silakarang Kederi", kec: "Sukawati", kab: "Gianyar" },
      { desa: "Perangsada", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Tojan", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Pinda Pering", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Patolan", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Sema", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Pering", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Keramas", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Medahan", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Cucukan", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Pasdalem", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Selat", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Belega", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Buruan", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Bangun Liman", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Celuk", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Getas Kawan", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Getas Kangin", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Kutri", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Geriya Ketandan", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Darmasanmata", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Saba", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Pinda", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Banda", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Bonbiyu", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Blangsinga", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Blahbatuh", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Teruna", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Satria", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Antugan", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Dharma Tiaga", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Bona", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Bedulu", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Taman", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Wanayu Mas", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Tegallinggah", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Margasengkala", kec: "Blahbatuh", kab: "Gianyar" },
      { desa: "Petak", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Mantring", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Padpadan", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Penyembahan", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Benawah", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Bonnyuh", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Madangan Kaja", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Madangan Kelod", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Uma Anyar", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Sumita", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Mulung", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Suwat", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Petak Jeruk", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Siangan", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Purnadesa", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Munduk", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Lokaserana", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Bandung", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Sawan", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Kabetan", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Bakbakan", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Gitgit", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Griya Sakti Kabetan", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Tegal tugu", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Sidan", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Tulikup Kaler", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Tulikup Kelod", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Temesi", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Lebih", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Kesian", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Serongga", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Pacung", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Bitera", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Batursari", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Beng", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Samplangan", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Bukitjangkrik", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Bukit Batu", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Selat", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Abianbase", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Tedung", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Gianyar", kec: "Gianyar", kab: "Gianyar" },
      { desa: "Kedewatan", kec: "Ubud", kab: "Gianyar" },
      { desa: "Bunutan", kec: "Ubud", kab: "Gianyar" },
      { desa: "Lungsiakan", kec: "Ubud", kab: "Gianyar" },
      { desa: "Payogan", kec: "Ubud", kab: "Gianyar" },
      { desa: "Tanggayuda", kec: "Ubud", kab: "Gianyar" },
      { desa: "Lodtunduh", kec: "Ubud", kab: "Gianyar" },
      { desa: "Gelogor", kec: "Ubud", kab: "Gianyar" },
      { desa: "Mawang", kec: "Ubud", kab: "Gianyar" },
      { desa: "Silungan", kec: "Ubud", kab: "Gianyar" },
      { desa: "Mas", kec: "Ubud", kab: "Gianyar" },
      { desa: "Abianseka", kec: "Ubud", kab: "Gianyar" },
      { desa: "Nyuh Kuning", kec: "Ubud", kab: "Gianyar" },
      { desa: "Pengosekan", kec: "Ubud", kab: "Gianyar" },
      { desa: "Peliatan", kec: "Ubud", kab: "Gianyar" },
      { desa: "Teges Kanginan", kec: "Ubud", kab: "Gianyar" },
      { desa: "Petulu", kec: "Ubud", kab: "Gianyar" },
      { desa: "Nagi", kec: "Ubud", kab: "Gianyar" },
      { desa: "Kutuh", kec: "Ubud", kab: "Gianyar" },
      { desa: "Laplapan", kec: "Ubud", kab: "Gianyar" },
      { desa: "Penestanan", kec: "Ubud", kab: "Gianyar" },
      { desa: "Sayan", kec: "Ubud", kab: "Gianyar" },
      { desa: "Demayu", kec: "Ubud", kab: "Gianyar" },
      { desa: "Kengetan", kec: "Ubud", kab: "Gianyar" },
      { desa: "Singakerta", kec: "Ubud", kab: "Gianyar" },
      { desa: "Tebongkang", kec: "Ubud", kab: "Gianyar" },
      { desa: "Tunon", kec: "Ubud", kab: "Gianyar" },
      { desa: "Bentuyung Sakti", kec: "Ubud", kab: "Gianyar" },
      { desa: "Junjungan", kec: "Ubud", kab: "Gianyar" },
      { desa: "Padang Tegal", kec: "Ubud", kab: "Gianyar" },
      { desa: "Taman Kaja", kec: "Ubud", kab: "Gianyar" },
      { desa: "Teggallantang", kec: "Ubud", kab: "Gianyar" },
      { desa: "Ubud", kec: "Ubud", kab: "Gianyar" },
      { desa: "Pejeng Kawan", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Pedapdapan", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Jero Kuta Pejeng", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Panglan", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Sawa Gunung", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Kelusu", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Patemon", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Sema Gading", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Gapokan", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Tri Eka Citta", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Uma Kuta", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Uma Dawa", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Tegalsaat", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Cagaan", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Tarukan", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Umahanyar", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Melayang", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Belusung", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Sanding", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Penendengan", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Sareseda", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Mantring", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Tampaksiring", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Bukit", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Kulub", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Kulu", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Eha", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Kelodan Tampaksiring", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Manukaya Let", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Manukaya Anyar", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Penempahan", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Malet", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Temen", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Basangambu", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Maniktawang", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Keranjangan", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Mancingan", kec: "Tampaksiring", kab: "Gianyar" },
      { desa: "Tegallalang", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Abangan", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Kelabangmoding", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Sapat", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Gentong", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Sebatu", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Talepud", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Pujung Sari", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Tumbakasa", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Jasan", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Bonjaka", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Jati", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Tegal Suci", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Apuh", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Keliki", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Sebali", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Taro Kaja", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Taro Kelod", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Ked", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Alas Pujung", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Belong", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Patas", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Pisang Kaja", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Pisang Kelod", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Let", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Sengkaduan", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Pakuseba", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Puakan", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Tebuana", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Tatag", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Calo", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Timbul", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Tegal Payang", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Perean", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Pupuan", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Tangkup", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Mumbi", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Kedisan", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Bayad", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Kebon", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Cebok", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Pakudui", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Dlod Blumbang", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Manuaba", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Kenderan", kec: "Tegallalang", kab: "Gianyar" },
      { desa: "Pengaji", kec: "Payangan", kab: "Gianyar" },
      { desa: "Begawan", kec: "Payangan", kab: "Gianyar" },
      { desa: "Tibekauh", kec: "Payangan", kab: "Gianyar" },
      { desa: "Bayad", kec: "Payangan", kab: "Gianyar" },
      { desa: "Payangan Desa", kec: "Payangan", kab: "Gianyar" },
      { desa: "Melinggih", kec: "Payangan", kab: "Gianyar" },
      { desa: "Sema", kec: "Payangan", kab: "Gianyar" },
      { desa: "Badung", kec: "Payangan", kab: "Gianyar" },
      { desa: "Geria", kec: "Payangan", kab: "Gianyar" },
      { desa: "Kelusa", kec: "Payangan", kab: "Gianyar" },
      { desa: "Keliki Kawan", kec: "Payangan", kab: "Gianyar" },
      { desa: "Yeh Tengah", kec: "Payangan", kab: "Gianyar" },
      { desa: "Bresela", kec: "Payangan", kab: "Gianyar" },
      { desa: "Bukian", kec: "Payangan", kab: "Gianyar" },
      { desa: "Subilang", kec: "Payangan", kab: "Gianyar" },
      { desa: "Tiyingan", kec: "Payangan", kab: "Gianyar" },
      { desa: "Ulapan", kec: "Payangan", kab: "Gianyar" },
      { desa: "Amo", kec: "Payangan", kab: "Gianyar" },
      { desa: "Dasong", kec: "Payangan", kab: "Gianyar" },
      { desa: "Lebah", kec: "Payangan", kab: "Gianyar" },
      { desa: "Lebah Buana", kec: "Payangan", kab: "Gianyar" },
      { desa: "Kebek", kec: "Payangan", kab: "Gianyar" },
      { desa: "Selasih", kec: "Payangan", kab: "Gianyar" },
      { desa: "Penginyahan", kec: "Payangan", kab: "Gianyar" },
      { desa: "Puhu", kec: "Payangan", kab: "Gianyar" },
      { desa: "Semaon", kec: "Payangan", kab: "Gianyar" },
      { desa: "Ponggang", kec: "Payangan", kab: "Gianyar" },
      { desa: "Satung", kec: "Payangan", kab: "Gianyar" },
      { desa: "Susut", kec: "Payangan", kab: "Gianyar" },
      { desa: "Buahan", kec: "Payangan", kab: "Gianyar" },
      { desa: "Jaang", kec: "Payangan", kab: "Gianyar" },
      { desa: "Gambih", kec: "Payangan", kab: "Gianyar" },
      { desa: "Sriteja", kec: "Payangan", kab: "Gianyar" },
      { desa: "Selat", kec: "Payangan", kab: "Gianyar" },
      { desa: "Gata", kec: "Payangan", kab: "Gianyar" },
      { desa: "Majangan", kec: "Payangan", kab: "Gianyar" },
      { desa: "Tengipis", kec: "Payangan", kab: "Gianyar" },
      { desa: "Pausan", kec: "Payangan", kab: "Gianyar" },
      { desa: "Singaperang", kec: "Payangan", kab: "Gianyar" },
      { desa: "Bada", kec: "Payangan", kab: "Gianyar" },
      { desa: "Kerta", kec: "Payangan", kab: "Gianyar" },
      { desa: "Marga Tengah", kec: "Payangan", kab: "Gianyar" },
      { desa: "Pilan", kec: "Payangan", kab: "Gianyar" },
      { desa: "Seming", kec: "Payangan", kab: "Gianyar" },
      { desa: "Penyabangan", kec: "Payangan", kab: "Gianyar" },
      { desa: "Saren", kec: "Payangan", kab: "Gianyar" },
      { desa: "Bunteh", kec: "Payangan", kab: "Gianyar" },
      { desa: "Mawang", kec: "Payangan", kab: "Gianyar" },
      { desa: "Bantiran", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Pupuan", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Pajahan", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Sai", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Munduktemu", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Anggasari", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Kebonjero", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Belatungan", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Antap Gawang", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Yeh Sibuh", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Pujungan", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Sanda", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Jelijih", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Punggang", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Penyawa", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Padangan", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Pempatan", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Batungsel", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Kebonpadangan", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Baletimbang", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Galiukir", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Karya Sari", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Suradadi", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Durentaluh", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Belimbing", kec: "Pupuan", kab: "Tabanan" },
      { desa: "Antosari", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Umaseka", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Petiles", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Banjar Anyar", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Dukuh", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Tiying gading", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Ampadan", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Antagana", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Mundeh", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Pasut", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Gelunggang", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Pancoran", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Nyuhgading", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Pengedan", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Bangal", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Auman", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Penataran", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Yeh Silah", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Delod Ceking", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Nagasari", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Lalanglinggah", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Suraberata", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Yeh Bakung", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Beja", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Bangkiang Jaran", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Bukit Tumpeng", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Lumbung Gede", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Cepaka", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Pengereregan", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Angkah", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Margatelu", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Wanayu", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Samsaman", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Selabih", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Semaja", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Banjar Bengkel", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Labak Suren", kec: "Selemadeg Barat", kab: "Tabanan" },
      { desa: "Sarinbuana", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Wanagiri", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Sawah", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Kebon Anyar", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Kebon Tumpalan", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Kebon Bantiran", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Mendek", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Kerta", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Pupuan Sawah", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Cangkup", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Kikian", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Pengesan", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Bajera", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Singin", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Gamongan", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Selemadeg", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Sukawati", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Berembeng", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Gablogan", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Cekik", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Bebali", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Munggu", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Baleagung", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Jembrana", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Antap Kaja", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Antap Delod Sema", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Soka", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Kutuh Paang", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Batulumbang", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Bonian", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Manikyang", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Cibukan", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Menungul", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Munduk", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Taman Yoga", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Kebon Lenganan", kec: "Selemadeg", kab: "Tabanan" },
      { desa: "Mambang Gede", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Dukuh Pulu Kaja", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Kelecung", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Bongan", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Munduk Ulan", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Tegal Mengkeb Kelod", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Tegal Mengkeb Kaja", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Gempinis", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Kulkul Batu", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Ketima", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Dalang Pondok", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Dalang", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Tanah Barak", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Serampingan", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Megati Kelod", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Megati Kaja", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Jelijih", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Sesandan", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Gunung Salak", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Bangkiang Sidem", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Apit Yeh", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Kemetug", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Kanciana", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Tangguntiti", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Bantas", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Munduk Malang", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Gadungan", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Pangkung Langkuas", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Munduk Pakel", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Cepaka", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Nyatnyatan", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Beraban", kec: "Selemadeg Timur", kab: "Tabanan" },
      { desa: "Kesiut Arca", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Kesiut Tengah", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Timpag", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Sambian", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Telaga Tunjung", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Meliling", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Sembung Gede", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Sarasidi", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Batuaji Kawan", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Dharma Sadhu Mandung", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Pacung", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Pelem Gede", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Samsam", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Dharma Kesatria Lumajang", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Kutuh Kaja", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Kutuh Kelod", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Eka Cita Penyalin", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Selingsing", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Serongga", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Pangkungkarung Gede", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Samsaman", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Dukuh Belong", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Bale Agung Kerambitan", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Tista", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Belumbang", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Tibubiyu", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Penarukan", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Kelating", kec: "Kerambitan", kab: "Tabanan" },
      { desa: "Wangaya Gede", kec: "Penebel", kab: "Tabanan" },
      { desa: "Keloncing", kec: "Penebel", kab: "Tabanan" },
      { desa: "Batu Kambing", kec: "Penebel", kab: "Tabanan" },
      { desa: "Bengkel", kec: "Penebel", kab: "Tabanan" },
      { desa: "Amplas", kec: "Penebel", kab: "Tabanan" },
      { desa: "Sandan", kec: "Penebel", kab: "Tabanan" },
      { desa: "Tengkudak", kec: "Penebel", kab: "Tabanan" },
      { desa: "Penganggahan", kec: "Penebel", kab: "Tabanan" },
      { desa: "Puluk-Puluk", kec: "Penebel", kab: "Tabanan" },
      { desa: "Puakan", kec: "Penebel", kab: "Tabanan" },
      { desa: "Tingkih Kerep", kec: "Penebel", kab: "Tabanan" },
      { desa: "Penatahan", kec: "Penebel", kab: "Tabanan" },
      { desa: "Mongan", kec: "Penebel", kab: "Tabanan" },
      { desa: "Tegayang", kec: "Penebel", kab: "Tabanan" },
      { desa: "Tegallinggah", kec: "Penebel", kab: "Tabanan" },
      { desa: "Sangketan", kec: "Penebel", kab: "Tabanan" },
      { desa: "Bongli", kec: "Penebel", kab: "Tabanan" },
      { desa: "Puring", kec: "Penebel", kab: "Tabanan" },
      { desa: "Banjar Anyar", kec: "Penebel", kab: "Tabanan" },
      { desa: "Munduk Dawa", kec: "Penebel", kab: "Tabanan" },
      { desa: "Munduk Bun", kec: "Penebel", kab: "Tabanan" },
      { desa: "Rejasa", kec: "Penebel", kab: "Tabanan" },
      { desa: "Pacut", kec: "Penebel", kab: "Tabanan" },
      { desa: "Kelembang", kec: "Penebel", kab: "Tabanan" },
      { desa: "Pesagi", kec: "Penebel", kab: "Tabanan" },
      { desa: "Cangkup", kec: "Penebel", kab: "Tabanan" },
      { desa: "Munduk Juwet", kec: "Penebel", kab: "Tabanan" },
      { desa: "Kuumkeladi", kec: "Penebel", kab: "Tabanan" },
      { desa: "Pagubugan Kangin", kec: "Penebel", kab: "Tabanan" },
      { desa: "Tegal Seka", kec: "Penebel", kab: "Tabanan" },
      { desa: "Riang Gede", kec: "Penebel", kab: "Tabanan" },
      { desa: "Jegu", kec: "Penebel", kab: "Tabanan" },
      { desa: "Ngis", kec: "Penebel", kab: "Tabanan" },
      { desa: "Buruan", kec: "Penebel", kab: "Tabanan" },
      { desa: "Benana", kec: "Penebel", kab: "Tabanan" },
      { desa: "Pitra", kec: "Penebel", kab: "Tabanan" },
      { desa: "Pohgending", kec: "Penebel", kab: "Tabanan" },
      { desa: "Serason", kec: "Penebel", kab: "Tabanan" },
      { desa: "Nyuling", kec: "Penebel", kab: "Tabanan" },
      { desa: "Asah", kec: "Penebel", kab: "Tabanan" },
      { desa: "Penebel", kec: "Penebel", kab: "Tabanan" },
      { desa: "Ubung", kec: "Penebel", kab: "Tabanan" },
      { desa: "Karandan", kec: "Penebel", kab: "Tabanan" },
      { desa: "Dukuh", kec: "Penebel", kab: "Tabanan" },
      { desa: "Sunantaya", kec: "Penebel", kab: "Tabanan" },
      { desa: "Gunung", kec: "Penebel", kab: "Tabanan" },
      { desa: "Biaung", kec: "Penebel", kab: "Tabanan" },
      { desa: "Pumahan", kec: "Penebel", kab: "Tabanan" },
      { desa: "Pemanis", kec: "Penebel", kab: "Tabanan" },
      { desa: "Cacab Jangkahan", kec: "Penebel", kab: "Tabanan" },
      { desa: "Tajen", kec: "Penebel", kab: "Tabanan" },
      { desa: "Cepik", kec: "Penebel", kab: "Tabanan" },
      { desa: "Babahan", kec: "Penebel", kab: "Tabanan" },
      { desa: "Utu", kec: "Penebel", kab: "Tabanan" },
      { desa: "Bolangan", kec: "Penebel", kab: "Tabanan" },
      { desa: "Dadia", kec: "Penebel", kab: "Tabanan" },
      { desa: "Mengesta", kec: "Penebel", kab: "Tabanan" },
      { desa: "Piling", kec: "Penebel", kab: "Tabanan" },
      { desa: "Kedampal", kec: "Penebel", kab: "Tabanan" },
      { desa: "Belulang", kec: "Penebel", kab: "Tabanan" },
      { desa: "Wongaya Betan", kec: "Penebel", kab: "Tabanan" },
      { desa: "Senganan Kanginan", kec: "Penebel", kab: "Tabanan" },
      { desa: "Senganan Kawan", kec: "Penebel", kab: "Tabanan" },
      { desa: "Pacung", kec: "Penebel", kab: "Tabanan" },
      { desa: "Pagi", kec: "Penebel", kab: "Tabanan" },
      { desa: "Munduk Paku", kec: "Penebel", kab: "Tabanan" },
      { desa: "Keridan", kec: "Penebel", kab: "Tabanan" },
      { desa: "Soka", kec: "Penebel", kab: "Tabanan" },
      { desa: "Belatung", kec: "Penebel", kab: "Tabanan" },
      { desa: "Bugbugan", kec: "Penebel", kab: "Tabanan" },
      { desa: "Jatiluwih", kec: "Penebel", kab: "Tabanan" },
      { desa: "Gunung Sari", kec: "Penebel", kab: "Tabanan" },
      { desa: "Kembang merta", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Pemuteran", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Batusesa", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Candikuning", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Bukitcatu", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Batunya", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Taman Tanda", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Juwuk Legi", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Abing", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Antapan", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Mayungan", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Tohjiwa", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Gelogor", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Angseri", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Munduk Lumbang", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Tegeh", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Apuan", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Tinungan", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Kambangan", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Jelantik", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Bangli", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Titigalar", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Apit Yeh", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Umapoh", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Sandan", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Munduk Andong", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Gunung Kangin", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Baturiti", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Pacung", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Bangah", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Abang", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Mojan", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Peneng", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Tundak", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Temacun", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Sekargula", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Kerobokan", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Luwus", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Punjuan", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Palian", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Poyan", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Mandul", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Perean", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Bunyuh", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Puseh", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Tuka", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Kukub", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Berteh", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Selat", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Basangbe", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Piun", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Beluangan", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Banjar Anyar", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Leba", kec: "Baturiti", kab: "Tabanan" },
      { desa: "Seribupati", kec: "Marga", kab: "Tabanan" },
      { desa: "Cau Belayu", kec: "Marga", kab: "Tabanan" },
      { desa: "Kekeran", kec: "Marga", kab: "Tabanan" },
      { desa: "Adeng", kec: "Marga", kab: "Tabanan" },
      { desa: "Pengembungan", kec: "Marga", kab: "Tabanan" },
      { desa: "Tegal Jadi", kec: "Marga", kab: "Tabanan" },
      { desa: "Kukuh", kec: "Marga", kab: "Tabanan" },
      { desa: "Belayu", kec: "Marga", kab: "Tabanan" },
      { desa: "Umabian", kec: "Marga", kab: "Tabanan" },
      { desa: "Kuwum Ancak", kec: "Marga", kab: "Tabanan" },
      { desa: "Kuwum", kec: "Marga", kab: "Tabanan" },
      { desa: "Ole", kec: "Marga", kab: "Tabanan" },
      { desa: "Kelaci", kec: "Marga", kab: "Tabanan" },
      { desa: "Marga", kec: "Marga", kab: "Tabanan" },
      { desa: "Payangan", kec: "Marga", kab: "Tabanan" },
      { desa: "Bunutin", kec: "Marga", kab: "Tabanan" },
      { desa: "Kalibalang", kec: "Marga", kab: "Tabanan" },
      { desa: "Gelagah", kec: "Marga", kab: "Tabanan" },
      { desa: "Petiga", kec: "Marga", kab: "Tabanan" },
      { desa: "Geluntung", kec: "Marga", kab: "Tabanan" },
      { desa: "Cau", kec: "Marga", kab: "Tabanan" },
      { desa: "Tua", kec: "Marga", kab: "Tabanan" },
      { desa: "Bayan", kec: "Marga", kab: "Tabanan" },
      { desa: "Baru", kec: "Marga", kab: "Tabanan" },
      { desa: "Pinge", kec: "Marga", kab: "Tabanan" },
      { desa: "Susut", kec: "Marga", kab: "Tabanan" },
      { desa: "Tengah", kec: "Marga", kab: "Tabanan" },
      { desa: "Tengah Kangin", kec: "Marga", kab: "Tabanan" },
      { desa: "Abiantuwung", kec: "Kediri", kab: "Tabanan" },
      { desa: "Kelaci Kelod", kec: "Kediri", kab: "Tabanan" },
      { desa: "Kelaci Kaja", kec: "Kediri", kab: "Tabanan" },
      { desa: "Suralaga", kec: "Kediri", kab: "Tabanan" },
      { desa: "Dalem yangApi", kec: "Kediri", kab: "Tabanan" },
      { desa: "Banjar Anyar", kec: "Kediri", kab: "Tabanan" },
      { desa: "Sanggulan", kec: "Kediri", kab: "Tabanan" },
      { desa: "Jadi", kec: "Kediri", kab: "Tabanan" },
      { desa: "Senapahan", kec: "Kediri", kab: "Tabanan" },
      { desa: "Buwit", kec: "Kediri", kab: "Tabanan" },
      { desa: "Kedungu", kec: "Kediri", kab: "Tabanan" },
      { desa: "Beraban", kec: "Kediri", kab: "Tabanan" },
      { desa: "Cepaka", kec: "Kediri", kab: "Tabanan" },
      { desa: "Kaba-Kaba", kec: "Kediri", kab: "Tabanan" },
      { desa: "Kediri", kec: "Kediri", kab: "Tabanan" },
      { desa: "Demung", kec: "Kediri", kab: "Tabanan" },
      { desa: "Batan Pole", kec: "Kediri", kab: "Tabanan" },
      { desa: "Mundeh", kec: "Kediri", kab: "Tabanan" },
      { desa: "Nyitdah", kec: "Kediri", kab: "Tabanan" },
      { desa: "Babakan", kec: "Kediri", kab: "Tabanan" },
      { desa: "Pandak Bandung", kec: "Kediri", kab: "Tabanan" },
      { desa: "Pandak Gede", kec: "Kediri", kab: "Tabanan" },
      { desa: "Pejaten", kec: "Kediri", kab: "Tabanan" },
      { desa: "Sandan Pondok", kec: "Tabanan", kab: "Tabanan" },
      { desa: "Sesandan", kec: "Tabanan", kab: "Tabanan" },
      { desa: "Sekartaji", kec: "Tabanan", kab: "Tabanan" },
      { desa: "Wanasari", kec: "Tabanan", kab: "Tabanan" },
      { desa: "Tunjuk", kec: "Tabanan", kab: "Tabanan" },
      { desa: "Buahan", kec: "Tabanan", kab: "Tabanan" },
      { desa: "Subamia", kec: "Tabanan", kab: "Tabanan" },
      { desa: "Kubontingguh", kec: "Tabanan", kab: "Tabanan" },
      { desa: "Dukuh Buahan", kec: "Tabanan", kab: "Tabanan" },
      { desa: "Bongan Puseh", kec: "Tabanan", kab: "Tabanan" },
      { desa: "Bedha", kec: "Tabanan", kab: "Tabanan" },
      { desa: "Yeh Gangga", kec: "Tabanan", kab: "Tabanan" },
      { desa: "Kota Tabanan", kec: "Tabanan", kab: "Tabanan" },
      { desa: "Tulamben", kec: "Kubu", kab: "Karangasem" },
      { desa: "Batudawa", kec: "Kubu", kab: "Karangasem" },
      { desa: "Muntig", kec: "Kubu", kab: "Karangasem" },
      { desa: "Dukuh", kec: "Kubu", kab: "Karangasem" },
      { desa: "Beluhu", kec: "Kubu", kab: "Karangasem" },
      { desa: "Kubu Juntal", kec: "Kubu", kab: "Karangasem" },
      { desa: "Baturinggit", kec: "Kubu", kab: "Karangasem" },
      { desa: "Bantas", kec: "Kubu", kab: "Karangasem" },
      { desa: "Kayuaya", kec: "Kubu", kab: "Karangasem" },
      { desa: "Bukit", kec: "Kubu", kab: "Karangasem" },
      { desa: "Lebah", kec: "Kubu", kab: "Karangasem" },
      { desa: "Karangsari", kec: "Kubu", kab: "Karangasem" },
      { desa: "Tigaron", kec: "Kubu", kab: "Karangasem" },
      { desa: "Nusu", kec: "Kubu", kab: "Karangasem" },
      { desa: "Ban", kec: "Kubu", kab: "Karangasem" },
      { desa: "Dlundungan", kec: "Kubu", kab: "Karangasem" },
      { desa: "Panek", kec: "Kubu", kab: "Karangasem" },
      { desa: "Cutcut", kec: "Kubu", kab: "Karangasem" },
      { desa: "Manik Aji", kec: "Kubu", kab: "Karangasem" },
      { desa: "Kaliaga", kec: "Kubu", kab: "Karangasem" },
      { desa: "Temakung", kec: "Kubu", kab: "Karangasem" },
      { desa: "Bonyoh", kec: "Kubu", kab: "Karangasem" },
      { desa: "Belong Plugon", kec: "Kubu", kab: "Karangasem" },
      { desa: "Belong Batu Kau", kec: "Kubu", kab: "Karangasem" },
      { desa: "Pucang", kec: "Kubu", kab: "Karangasem" },
      { desa: "Daya", kec: "Kubu", kab: "Karangasem" },
      { desa: "Jatituhu", kec: "Kubu", kab: "Karangasem" },
      { desa: "Cegi", kec: "Kubu", kab: "Karangasem" },
      { desa: "Pengalusan", kec: "Kubu", kab: "Karangasem" },
      { desa: "Perasan", kec: "Kubu", kab: "Karangasem" },
      { desa: "Asti", kec: "Kubu", kab: "Karangasem" },
      { desa: "Darmaji", kec: "Kubu", kab: "Karangasem" },
      { desa: "Bunga", kec: "Kubu", kab: "Karangasem" },
      { desa: "Tianyar", kec: "Kubu", kab: "Karangasem" },
      { desa: "Paleg Kelod", kec: "Kubu", kab: "Karangasem" },
      { desa: "Paleg Kaja", kec: "Kubu", kab: "Karangasem" },
      { desa: "Penginyahan", kec: "Kubu", kab: "Karangasem" },
      { desa: "Pedahan Kelod", kec: "Kubu", kab: "Karangasem" },
      { desa: "Pedahan Kaja", kec: "Kubu", kab: "Karangasem" },
      { desa: "Krebelahan", kec: "Kubu", kab: "Karangasem" },
      { desa: "Munti Gunung", kec: "Kubu", kab: "Karangasem" },
      { desa: "Ababi", kec: "Abang", kab: "Karangasem" },
      { desa: "Tiyingtali", kec: "Abang", kab: "Karangasem" },
      { desa: "Tauka", kec: "Abang", kab: "Karangasem" },
      { desa: "Tuminggal", kec: "Abang", kab: "Karangasem" },
      { desa: "Gamongan", kec: "Abang", kab: "Karangasem" },
      { desa: "Tanah Aji", kec: "Abang", kab: "Karangasem" },
      { desa: "Kesimpar", kec: "Abang", kab: "Karangasem" },
      { desa: "Tista", kec: "Abang", kab: "Karangasem" },
      { desa: "Ngis", kec: "Abang", kab: "Karangasem" },
      { desa: "Purwayu", kec: "Abang", kab: "Karangasem" },
      { desa: "Basangalas", kec: "Abang", kab: "Karangasem" },
      { desa: "Linggawana", kec: "Abang", kab: "Karangasem" },
      { desa: "Culik", kec: "Abang", kab: "Karangasem" },
      { desa: "Bebayu", kec: "Abang", kab: "Karangasem" },
      { desa: "Paselatan", kec: "Abang", kab: "Karangasem" },
      { desa: "Datah", kec: "Abang", kab: "Karangasem" },
      { desa: "Kedampal", kec: "Abang", kab: "Karangasem" },
      { desa: "Tukad Besi", kec: "Abang", kab: "Karangasem" },
      { desa: "Sega", kec: "Abang", kab: "Karangasem" },
      { desa: "Gulinten", kec: "Abang", kab: "Karangasem" },
      { desa: "Bugbug", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Perasi", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Asak", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Timbrah", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Bukit", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Jumenang", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Sekargunung", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Batugunung", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Kebon Bukit", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Tumbu", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Seraya", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Karangasem", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Ujung Hyang", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Susuan", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Tampuagan", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Dukuh Penaban", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Subagan", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Jasri", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Padangkerta", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Kertasari", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Dukuh", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Temega", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Peladung", kec: "Karangasem", kab: "Karangasem" },
      { desa: "Sibetan", kec: "Bebandem", kab: "Karangasem" },
      { desa: "Macang", kec: "Bebandem", kab: "Karangasem" },
      { desa: "Bungaya", kec: "Bebandem", kab: "Karangasem" },
      { desa: "Saren", kec: "Bebandem", kab: "Karangasem" },
      { desa: "Budakeling", kec: "Bebandem", kab: "Karangasem" },
      { desa: "Bebandem", kec: "Bebandem", kab: "Karangasem" },
      { desa: "Tohpati", kec: "Bebandem", kab: "Karangasem" },
      { desa: "Kastala", kec: "Bebandem", kab: "Karangasem" },
      { desa: "Liligundi", kec: "Bebandem", kab: "Karangasem" },
      { desa: "Jungsri", kec: "Bebandem", kab: "Karangasem" },
      { desa: "Komala", kec: "Bebandem", kab: "Karangasem" },
      { desa: "Nangka", kec: "Bebandem", kab: "Karangasem" },
      { desa: "Umanyar", kec: "Bebandem", kab: "Karangasem" },
      { desa: "Tanah Aron", kec: "Bebandem", kab: "Karangasem" },
      { desa: "Poh", kec: "Bebandem", kab: "Karangasem" },
      { desa: "Gegelang", kec: "Manggis", kab: "Karangasem" },
      { desa: "Angantelu", kec: "Manggis", kab: "Karangasem" },
      { desa: "Padangbai", kec: "Manggis", kab: "Karangasem" },
      { desa: "Ulakan", kec: "Manggis", kab: "Karangasem" },
      { desa: "Tanahampo", kec: "Manggis", kab: "Karangasem" },
      { desa: "Manggis", kec: "Manggis", kab: "Karangasem" },
      { desa: "Apityeh", kec: "Manggis", kab: "Karangasem" },
      { desa: "Yehpoh", kec: "Manggis", kab: "Karangasem" },
      { desa: "Buitan", kec: "Manggis", kab: "Karangasem" },
      { desa: "Selumbung", kec: "Manggis", kab: "Karangasem" },
      { desa: "Bukit Catu", kec: "Manggis", kab: "Karangasem" },
      { desa: "Ngis", kec: "Manggis", kab: "Karangasem" },
      { desa: "Pekarangan", kec: "Manggis", kab: "Karangasem" },
      { desa: "Nyuh Tebel", kec: "Manggis", kab: "Karangasem" },
      { desa: "Tenganan Pegringsingan", kec: "Manggis", kab: "Karangasem" },
      { desa: "Tenganan Dauh Tukad", kec: "Manggis", kab: "Karangasem" },
      { desa: "Gumung", kec: "Manggis", kab: "Karangasem" },
      { desa: "Sengkidu", kec: "Manggis", kab: "Karangasem" },
      { desa: "Pasedahan", kec: "Manggis", kab: "Karangasem" },
      { desa: "Muncan", kec: "Selat", kab: "Karangasem" },
      { desa: "Yeha", kec: "Selat", kab: "Karangasem" },
      { desa: "Ancut", kec: "Selat", kab: "Karangasem" },
      { desa: "Pura", kec: "Selat", kab: "Karangasem" },
      { desa: "Lebih", kec: "Selat", kab: "Karangasem" },
      { desa: "Telung Buana", kec: "Selat", kab: "Karangasem" },
      { desa: "Badeg Tengah", kec: "Selat", kab: "Karangasem" },
      { desa: "Badeg Kelodan", kec: "Selat", kab: "Karangasem" },
      { desa: "Sogra", kec: "Selat", kab: "Karangasem" },
      { desa: "Sebudi", kec: "Selat", kab: "Karangasem" },
      { desa: "Bukit Galah", kec: "Selat", kab: "Karangasem" },
      { desa: "Sebun", kec: "Selat", kab: "Karangasem" },
      { desa: "Taman Darma", kec: "Selat", kab: "Karangasem" },
      { desa: "Padangaji", kec: "Selat", kab: "Karangasem" },
      { desa: "Umacetra", kec: "Selat", kab: "Karangasem" },
      { desa: "Sukaluwih", kec: "Selat", kab: "Karangasem" },
      { desa: "Tegeh", kec: "Selat", kab: "Karangasem" },
      { desa: "Presana", kec: "Selat", kab: "Karangasem" },
      { desa: "Selat", kec: "Selat", kab: "Karangasem" },
      { desa: "Santi", kec: "Selat", kab: "Karangasem" },
      { desa: "Duda", kec: "Selat", kab: "Karangasem" },
      { desa: "Padang Tunggal", kec: "Selat", kab: "Karangasem" },
      { desa: "Karangsari", kec: "Selat", kab: "Karangasem" },
      { desa: "Geriana Kangin", kec: "Selat", kab: "Karangasem" },
      { desa: "Geriana Kauh", kec: "Selat", kab: "Karangasem" },
      { desa: "Putung", kec: "Selat", kab: "Karangasem" },
      { desa: "Pateh", kec: "Selat", kab: "Karangasem" },
      { desa: "Buyan", kec: "Rendang", kab: "Karangasem" },
      { desa: "Menanga", kec: "Rendang", kab: "Karangasem" },
      { desa: "Suwukan", kec: "Rendang", kab: "Karangasem" },
      { desa: "Pejeng", kec: "Rendang", kab: "Karangasem" },
      { desa: "Tegenan", kec: "Rendang", kab: "Karangasem" },
      { desa: "Batusesa", kec: "Rendang", kab: "Karangasem" },
      { desa: "Buk Cabe", kec: "Rendang", kab: "Karangasem" },
      { desa: "Pempatan", kec: "Rendang", kab: "Karangasem" },
      { desa: "Pemuteran", kec: "Rendang", kab: "Karangasem" },
      { desa: "Putung", kec: "Rendang", kab: "Karangasem" },
      { desa: "Kubakal", kec: "Rendang", kab: "Karangasem" },
      { desa: "Alasngandang", kec: "Rendang", kab: "Karangasem" },
      { desa: "Waringin", kec: "Rendang", kab: "Karangasem" },
      { desa: "Geliang", kec: "Rendang", kab: "Karangasem" },
      { desa: "Pule", kec: "Rendang", kab: "Karangasem" },
      { desa: "Teges", kec: "Rendang", kab: "Karangasem" },
      { desa: "Besakih", kec: "Rendang", kab: "Karangasem" },
      { desa: "Kesimpar", kec: "Rendang", kab: "Karangasem" },
      { desa: "Temukus", kec: "Rendang", kab: "Karangasem" },
      { desa: "Tarib", kec: "Rendang", kab: "Karangasem" },
      { desa: "Tukad Belah", kec: "Rendang", kab: "Karangasem" },
      { desa: "Rendang", kec: "Rendang", kab: "Karangasem" },
      { desa: "Pedukuhan", kec: "Rendang", kab: "Karangasem" },
      { desa: "Nongan", kec: "Rendang", kab: "Karangasem" },
      { desa: "Segah", kec: "Rendang", kab: "Karangasem" },
      { desa: "Pesaban", kec: "Rendang", kab: "Karangasem" },
      { desa: "Iseh", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Tebola", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Kebung", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Telun Wayah", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Sukahet", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Delod Yeh", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Lebu", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Toh Jiwa", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Wangsean", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Klungah", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Tangkup Desa", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Tangkup Anyar", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Tabu", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Sangkungan", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Sangkan Gunung", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Sanggem", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Dukuh", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Mijil", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Ipah", kec: "Sidemen", kab: "Karangasem" },
      { desa: "Tohpati", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Bungbungan", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Jungut", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Penarukan", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Nyalian", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Pemenang", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Uma Anyar", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Tegalwangi", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Bakas", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Tusan", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Griya Budha", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Sema Agung", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Banjarangkan", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Koripan Tengah", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Negari", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Sarimertha", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Takmung", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Sidayu Tojan", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Sidayu Nyuhaya", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Umasalakan", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Lepang", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Banda", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Tihingan", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Penasan", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Pau", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Getakan", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Anjingan", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Aan", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Sengkiding", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Timuhun", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Nyanglan", kec: "Banjarangkan", kab: "Klungkung" },
      { desa: "Selisihan", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Apet", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Tabu Banjaraan", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Cucukan", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Gembalan", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Payungan", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Takedan", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Selat", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Jumpai", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Akah", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Manduang", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Tegak", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Bajing", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Tulang Nyuh", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Satra", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Tangkas", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Gelgel", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Sangkanbuana", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Budaga", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Kemoning", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Besang Kangin", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Besang Kawan Tohjiwa", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Semarapura", kec: "Klungkung", kab: "Klungkung" },
      { desa: "Besan", kec: "Dawan", kab: "Klungkung" },
      { desa: "Dawan", kec: "Dawan", kab: "Klungkung" },
      { desa: "Gelogor", kec: "Dawan", kab: "Klungkung" },
      { desa: "Pikat", kec: "Dawan", kab: "Klungkung" },
      { desa: "Pangi", kec: "Dawan", kab: "Klungkung" },
      { desa: "Pesinggahan", kec: "Dawan", kab: "Klungkung" },
      { desa: "Punduk Dawa", kec: "Dawan", kab: "Klungkung" },
      { desa: "Gunaksa", kec: "Dawan", kab: "Klungkung" },
      { desa: "Sulang", kec: "Dawan", kab: "Klungkung" },
      { desa: "Mincidan", kec: "Dawan", kab: "Klungkung" },
      { desa: "Gerombong", kec: "Dawan", kab: "Klungkung" },
      { desa: "Tribuana", kec: "Dawan", kab: "Klungkung" },
      { desa: "Bias", kec: "Dawan", kab: "Klungkung" },
      { desa: "Pancingan", kec: "Dawan", kab: "Klungkung" },
      { desa: "Kusamba", kec: "Dawan", kab: "Klungkung" },
      { desa: "Karangdadi", kec: "Dawan", kab: "Klungkung" },
      { desa: "Pasurungan", kec: "Dawan", kab: "Klungkung" },
      { desa: "Pande", kec: "Dawan", kab: "Klungkung" },
      { desa: "Sangging", kec: "Dawan", kab: "Klungkung" },
      { desa: "Sampalan", kec: "Dawan", kab: "Klungkung" },
      { desa: "Sekartaji", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Kertha Parisudha", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Tri Wahama Eka Winangun", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Mastulan", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Panca Buana Santi", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Tri Wana Giri Mandala", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Ped", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Nyuh Kukuh", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Biaung", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Sakti", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Sebunibus", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Batu Madeg", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Penutuk", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Mujaning Tembeling", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Tri Buana Sekar Sari", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Klumpu", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Panca Mekar Sari", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Panca Madala Gita", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Sekar Pandan", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Batukandik", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Tri Wahana Dharma", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Kertha Buwana", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Dalem Setra Batununggul", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Batumulapan", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Kutapang", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Tanglad", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Anta", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Wates", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Gepuh", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Suana", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Karangsari", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Semaya", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Kelemahan", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Jungutbatu", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Lembongan", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Sandhi Bhuana", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Kutampi", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Limo", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Bunga Mekar", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Sebuluh", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Pundukahan Kaja", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Sompang", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Dwi Kukuh Lestari", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Pejukutan", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Pelilit", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Karang", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Ampel", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Panca Sakti", kec: "Nusa Penida", kab: "Klungkung" },
      { desa: "Kedua", kec: "Denpasar Utara", kab: "Denpasar" },
      { desa: "Peninjoan", kec: "Denpasar Utara", kab: "Denpasar" },
      { desa: "Cengkilung", kec: "Denpasar Utara", kab: "Denpasar" },
      { desa: "Jenah", kec: "Denpasar Utara", kab: "Denpasar" },
      { desa: "Peraupan", kec: "Denpasar Utara", kab: "Denpasar" },
      { desa: "Pohgading", kec: "Denpasar Utara", kab: "Denpasar" },
      { desa: "Peguyangan", kec: "Denpasar Utara", kab: "Denpasar" },
      { desa: "Tonja", kec: "Denpasar Utara", kab: "Denpasar" },
      { desa: "Oongan", kec: "Denpasar Utara", kab: "Denpasar" },
      { desa: "Ubung", kec: "Denpasar Utara", kab: "Denpasar" },
      { desa: "Taman Pohmanis", kec: "Denpasar Timur", kab: "Denpasar" },
      { desa: "Laplap", kec: "Denpasar Timur", kab: "Denpasar" },
      { desa: "Bekul", kec: "Denpasar Timur", kab: "Denpasar" },
      { desa: "Yangbatu", kec: "Denpasar Timur", kab: "Denpasar" },
      { desa: "Pagan", kec: "Denpasar Timur", kab: "Denpasar" },
      { desa: "Tanjung Bungkak", kec: "Denpasar Timur", kab: "Denpasar" },
      { desa: "Kesiman", kec: "Denpasar Timur", kab: "Denpasar" },
      { desa: "Penatih", kec: "Denpasar Timur", kab: "Denpasar" },
      { desa: "Penatih Puri", kec: "Denpasar Timur", kab: "Denpasar" },
      { desa: "Anggabaya", kec: "Denpasar Timur", kab: "Denpasar" },
      { desa: "Tambawu", kec: "Denpasar Timur", kab: "Denpasar" },
      { desa: "Sumerta", kec: "Denpasar Timur", kab: "Denpasar" },
      { desa: "Pemogan", kec: "Denpasar Selatan", kab: "Denpasar" },
      { desa: "Kepaon", kec: "Denpasar Selatan", kab: "Denpasar" },
      { desa: "Sidakarya", kec: "Denpasar Selatan", kab: "Denpasar" },
      { desa: "Penyaringan", kec: "Denpasar Selatan", kab: "Denpasar" },
      { desa: "Sanur", kec: "Denpasar Selatan", kab: "Denpasar" },
      { desa: "Pedungan", kec: "Denpasar Selatan", kab: "Denpasar" },
      { desa: "Sesetan", kec: "Denpasar Selatan", kab: "Denpasar" },
      { desa: "Serangan", kec: "Denpasar Selatan", kab: "Denpasar" },
      { desa: "Panjer", kec: "Denpasar Selatan", kab: "Denpasar" },
      { desa: "Renon", kec: "Denpasar Selatan", kab: "Denpasar" },
      { desa: "Intaran", kec: "Denpasar Selatan", kab: "Denpasar" },
      { desa: "Denpasar", kec: "Denpasar Barat", kab: "Denpasar" },
      { desa: "Padangsambian", kec: "Denpasar Barat", kab: "Denpasar" }
    ];

    console.log("Memulai proses seeding wilayah di Bali...");

    // Mulai transaksi untuk keamanan data
    t = await db.transaction();

    // Find or Create Provinsi
    const [provinsi] = await Provinsi.findOrCreate({
      where: {
        nama_provinsi: "BALI"
      },
      transaction: t
    });

    for (const item of rawData) {
      // 1. Find or Create Kabupaten
      const [kabupaten] = await Kabupaten.findOrCreate({
        where: { 
          nama_kabupaten: item.kab.trim().toUpperCase(),
          provinsi_id: provinsi.id
        },
        transaction: t
      });
      // 2. Find or Create Kecamatan
      const [kecamatan] = await Kecamatan.findOrCreate({
        where: { 
          nama_kecamatan: item.kec.trim().toUpperCase(),
          kabupaten_id: kabupaten.id 
        },
        transaction: t
      });
      // 3. Create Desa Adat
      await DesaAdat.findOrCreate({
        where: { 
          nama_desa_adat: item.desa.trim().toUpperCase(),
          kecamatan_id: kecamatan.id 
        },
        transaction: t
      });
    }

    await t.commit();
    console.log("Seeding wilayah di Bali berhasil diselesaikan.");
  } catch (error) {
    if (t) {
      await t.rollback();
    }
    console.log("Seeding wilayah di Bali gagal dilakukan:", error);
  }
};